erDiagram

    User {
        string screen_name
        string email
        string password
        integer wins 
    }

    GridGame {
        integer score
    }

    User ||--o{ GridGame : "has many"